irrad-data-manager/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # Examples:
    # url(r'^$', 'test2_samples_manager.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'', include('samples_manager.urls', namespace="samples_manager")),
    #url(r'^samples_manager/',
    #    include('samples_manager.urls', namespace="samples_manager")),
    url(r'^admin/', admin.site.urls),
    #url(r'^terms_conditions/',
    #    TemplateView.as_view(template_name='terms_conditions.html'),
    #    name='terms_conditions'),
    #url(r'^fluence_conversion/',
    #    TemplateView.as_view(template_name='fluence_conversion.html'),
    #    name='fluence_conversion'),
]

samples_manager/urls.py
    url(r'^boxes/(?P<pk>\d+)/items/add/$', box_views.box_items_add, name='box_items_add'),
    url(r'^boxes/(?P<pk>\d+)/items/remove/$', box_views.box_item_remove, name='box_item_remove'),
    url(r'^boxes/(?P<pk>\d+)/items/search/$', box_views.box_items_search, name='box_items_search'),
    url(r'^boxes/clone/$', box_views.box_clone, name='box_clone'),
    url(r'^boxes/create/$', box_views.box_create, name='box_create'),
    url(r'^boxes/delete/$', box_views.box_delete, name='box_delete'),
    url(r'^boxes/details/$', box_views.redirect_box_details, name='redirect_box_details'),
    url(r'^boxes/items/$', box_views.redirect_box_items_list, name='redirect_box_items_list'),
    url(r'^boxes/read_infoream/$', box_views.box_read_infoream, name='box_read_infoream'),
    url(r'^boxes/search/$', box_views.boxes_search, name='boxes_search'),
    url(r'^boxes/update/$', box_views.box_update, name='box_update'),
    url(r'^boxes/write_infoream/$', box_views.box_write_infoream, name='box_write_infoream'),
    url(r'^compounds/$', compound_views.compounds_list, name='compounds_list'),
    url(r'^compounds/create/$', compound_views.compound_create, name='compound_create'),
    url(r'^compounds/delete/$', compound_views.compound_delete, name='compound_delete'),
    url(r'^compounds/search/$', compound_views.compounds_search, name='compounds_search'),
    url(r'^compounds/update/$', compound_views.compound_update, name='compound_update'),
    url(r'^dosimeters/$', dosimeter_views.dosimeters_list, name='dosimeters_list'),
    url(r'^dosimeters/(?P<pk>\d+)/details/$', dosimeter_views.dosimeter_details, name='dosimeter_details'),
    url(r'^dosimeters/attach_box/$', dosimeter_views.dosimeter_attach_box, name='dosimeter_attach_box'),
    url(r'^dosimeters/clone/$', dosimeter_views.dosimeter_clone, name='dosimeter_clone'),
    url(r'^dosimeters/create/$', dosimeter_views.dosimeter_create, name='dosimeter_create'),
    url(r'^dosimeters/delete/$', dosimeter_views.dosimeter_delete, name='dosimeter_delete'),
    url(r'^dosimeters/details/$', dosimeter_views.redirect_dosimeter_details, name='redirect_dosimeter_details'),
    url(r'^dosimeters/generate_ids/$', dosimeter_views.create_dos_ids, name='create_dos_ids'),
    url(r'^dosimeters/read_infoream/$', dosimeter_views.dosimeter_read_infoream, name='dosimeter_read_infoream'),
    url(r'^dosimeters/search/$', dosimeter_views.dosimeters_search, name='dosimeters_search'),
    url(r'^dosimeters/update/$', dosimeter_views.dosimeter_update, name='dosimeter_update'),
    url(r'^dosimeters/write_infoream/$', dosimeter_views.dosimeter_write_infoream, name='dosimeter_write_infoream'),
    url(r'^dosimetry_results/$', irradiation_views.dosimetry_results_list, name='dosimetry_results_list'),
    url(r'^dosimetry_results/search/$', irradiation_views.dosimetry_results_search, name='dosimetry_results_search'),
    url(r'^equipment/print/$', views.equipment_print, name='equipment_print'),
    url(r'^experiments/$', experiment_views.experiments_list, name='experiments_list'),
    url(r'^experiments/(?P<experiment_id>\d+)/samples/(?P<pk>\d+)/details/$', sample_views.sample_details, name='sample_details'),
    url(r'^experiments/(?P<pk>\d+)/$', experiment_views.experiment_details, name='experiment_details'),
    url(r'^experiments/(?P<pk>\d+)/comment/$', experiment_views.experiment_comment_update, name='experiment_comment_update'),
    url(r'^experiments/(?P<pk>\d+)/samples/$', sample_views.experiment_samples_list, name='experiment_samples_list'),
    url(r'^experiments/(?P<pk>\d+)/samples/archive/$', sample_views.experiment_samples_archive, name='experiment_samples_archive'),
    url(r'^experiments/(?P<pk>\d+)/samples/assign_set_ids/$', sample_views.assign_set_ids, name='assign_set_ids'),
    url(r'^experiments/(?P<pk>\d+)/samples/attach_box/$', sample_views.sample_attach_box, name='sample_attach_box'),
    url(r'^experiments/(?P<pk>\d+)/samples/clone/$', sample_views.sample_clone, name='sample_clone'),
    url(r'^experiments/(?P<pk>\d+)/samples/create/$', sample_views.sample_create, name='sample_create'),
    url(r'^experiments/(?P<pk>\d+)/samples/delete/$', sample_views.sample_delete, name='sample_delete'),
    url(r'^experiments/(?P<pk>\d+)/samples/details/$', sample_views.redirect_sample_details, name='redirect_sample_details'),
    url(r'^experiments/(?P<pk>\d+)/samples/group_irradiation_create/$', irradiation_views.group_irradiation_create, name='group_irradiation_create'),
    url(r'^experiments/(?P<pk>\d+)/samples/read_infoream/$', sample_views.sample_read_infoream, name='sample_read_infoream'),
    url(r'^experiments/(?P<pk>\d+)/samples/results/$', sample_views.sample_results, name='sample_results'),
    url(r'^experiments/(?P<pk>\d+)/samples/sample_move/$', sample_views.sample_move, name='sample_move'),
    url(r'^experiments/(?P<pk>\d+)/samples/search/$', sample_views.samples_search, name='experiment_samples_search'),
    url(r'^experiments/(?P<pk>\d+)/samples/update/$', sample_views.sample_update, name='sample_update'),
    url(r'^experiments/(?P<pk>\d+)/samples/write_infoream/$', sample_views.sample_write_infoream, name='sample_write_infoream'),
    url(r'^experiments/(?P<pk>\d+)/user/add/$', user_views.add_experiment_user, name='add_experiment_user'),
    url(r'^experiments/(?P<pk>\d+)/users/$', user_views.experiment_users_list, name='experiment_users_list'),
    url(r'^experiments/(?P<pk>\d+)/users/remove/$', user_views.remove_experiment_user, name='remove_experiment_user'),
    url(r'^experiments/(?P<pk>\d+)/users/search/$', user_views.experiment_users_search, name='experiment_users_search'),
    url(r'^experiments/clone/$', experiment_views.experiment_clone, name='experiment_clone'),
    url(r'^experiments/contact_responsible/$', experiment_views.redirect_experiment_contact_responsible, name='redirect_experiment_contact_responsible'),
    url(r'^experiments/create/$', experiment_views.experiment_create, name='experiment_create'),
    url(r'^experiments/delete/$', experiment_views.experiment_delete, name='experiment_delete'),
    url(r'^experiments/details/$', experiment_views.redirect_experiment_details, name='redirect_experiment_details'),
    url(r'^experiments/samples/$', experiment_views.redirect_experiment_samples_list, name='redirect_experiment_samples_list'),
    url(r'^experiments/search/$', experiment_views.experiments_search, name='experiments_search'),
    url(r'^experiments/shared/$', experiment_views.experiments_shared_list, name='experiments_shared_list'),
    url(r'^experiments/shared/search/$', experiment_views.experiments_shared_search, name='experiments_shared_search'),
    url(r'^experiments/status/$', experiment_views.experiment_status_update, name='experiment_status_update'),
    url(r'^experiments/update/$', experiment_views.experiment_update, name='experiment_update'),
    url(r'^experiments/upload_attachment/$', experiment_views.experiment_upload_attachment, name='experiment_upload_attachment'),
    url(r'^experiments/users/$', experiment_views.redirect_experiment_users_list, name='redirect_experiment_users_list'),
    url(r'^experiments/validate/$', experiment_views.experiment_validate, name='experiment_validate'),
    url(r'^experiments/visibility/$', experiment_views.experiment_update_visibility, name='experiment_update_visibility'),
    url(r'^fluence_conversion/$', views.fluence_conversion, name='fluence_conversion'),
    url(r'^fluence_factors/$', fluence_factor_views.fluence_factors_list, name='fluence_factors_list'),
    url(r'^fluence_factors/create/$', fluence_factor_views.fluence_factor_create, name='fluence_factor_create'),
    url(r'^fluence_factors/delete/$', fluence_factor_views.fluence_factor_delete, name='fluence_factor_delete'),
    url(r'^fluence_factors/update/$', fluence_factor_views.fluence_factor_update, name='fluence_factor_update'),
    url(r'^get_locations/$',views.get_locations, name='get_locations'),
    url(r'^irradiations/$', irradiation_views.irradiations_list, name='irradiations_list'),
    url(r'^irradiations/beam_status_toggle/$', irradiation_views.irradiation_in_beam_status_update, name='irradiation_in_beam_status_update'),
    url(r'^irradiations/create/$', irradiation_views.irradiation_create, name='irradiation_create'),
    url(r'^irradiations/delete/$', irradiation_views.irradiation_delete, name='irradiation_delete'),
    url(r'^irradiations/search/$', irradiation_views.irradiations_search, name='irradiations_search'),
    url(r'^irradiations/select_table/$', irradiation_views.select_table, name='select_table'),
    url(r'^irradiations/status_update/$', irradiation_views.irradiation_status_update, name='irradiation_status_update'),
    url(r'^irradiations/update/$', irradiation_views.irradiation_update, name='irradiation_update'),
    url(r'^irradiations/update_sec/$', irradiation_views.update_sec, name='irradiations_update_sec'),
    url(r'^list_filter/$',views.list_filter, name='list_filter'),
    url(r'^logged_user/$', user_views.view_user, name='view_user'),
    url(r'^read_infoream/(?P<equipment_id>.*)/$', views.read_equipment_from_infoream, name='read_equipment_infoream'),
    url(r'^regulations/$',views.regulations, name='regulations'),
    url(r'^samples/$',sample_views.admin_samples_list, name='admin_samples_list'),
    url(r'^samples/(?P<pk>\d+)/dosimetry/results/$', irradiation_views.sample_dosimetry_results, name='sample_dosimetry_results'),
    url(r'^test/$', views.test, name='test'),
    url(r'^users/$', user_views.users_list, name='users_list'),
    url(r'^users/(?P<pk>\d+)/experiments/$', experiment_views.admin_experiments_user_view, name='admin_experiments_user_view'),
    url(r'^users/create/$', user_views.user_create, name='user_create'),
    url(r'^users/delete/$', user_views.user_delete, name='user_delete'),
    url(r'^users/search/$', user_views.users_search, name='users_search'),
    url(r'^users/update/$', user_views.user_update, name='user_update'),

samples_manager/templates/samples_manager/dosimeter_details.html
{% extends 'samples_manager/base_details.html' %}
{% load custom_filters %}

{% block breadcrumb %}
<a class='section' href='{% url "samples_manager:index" %}'>Home</a>
<div class='divider'> / </div>
<a class='section' href='{% url "samples_manager:dosimeters_list" %}'>Dosimeters</a>
<div class='divider'> / </div>
<div class='active section'>Details {{ dosimeter.dos_id }}</div>
{% endblock %}

{% block partial_template %}
<div class='ui two column grid'>
    <div class='column'>
        <div class='ui segment'>
            <div class='ui divided selection list'>
                <div class='item'>
                    <div class='ui horizontal label'>
                        ID
                    </div>
                    {{dosimeter.dos_id}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Responsible
                    </div>
                    {{dosimeter.responsible.email}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Location
                    </div>
                    {{dosimeter.current_location}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Dimensions
                    </div>
                        {{dosimeter.width|num_notation:'4d'}} x {{dosimeter.height|num_notation:'4d'}} x {{dosimeter.length|num_notation:'4d'}} (wxhxl mm) 
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Foils Number
                    </div>
                    {{dosimeter.foils_number}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Weight
                    </div>
                    {{dosimeter.weight|num_notation:'4d'}} g
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Status
                    </div>
                    {{dosimeter.status}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Type
                    </div>
                    {{dosimeter.dos_type}}
                </div>
            </div>
        </div>
    </div>
    <div class='column'>
        <div class='ui segment'>
            <div class='ui divided selection list'>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Box
                    </div>
                    {%if dosimeter.box %}
                    <a href='{% url "samples_manager:box_details" dosimeter.box.id %}'>{{dosimeter.box.box_id}}</a>
                    {% endif %}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Parent Dosimeter
                    </div>
                    {%if dosimeter.parent_dosimeter %}
                    <a href='{% url "samples_manager:dosimeter_details" dosimeter.parent_dosimeter.id %}'>{{dosimeter.parent_dosimeter.dos_id}}</a>
                    {% endif %}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Created at
                    </div>
                    {{dosimeter.created_at}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Updated at
                    </div>
                    {{dosimeter.updated_at}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Created by
                    </div>
                    {{dosimeter.created_by}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Updated by
                    </div>
                    {{dosimeter.updated_by}}
                </div>
                <div class='item'>
                    <div class='ui horizontal label'>
                        Comments
                    </div>
                    {{dosimeter.comments}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

samples_manager/templates/samples_manager/form_collapsible_text.html
{% if additional_text %}
    <p class='warning-text text-toggle hidden'>{{ additional_text.uncollapsed|linebreaksbr }}<br><a class='text-toggle-action' href=''>show less</a></p>
    <p class='warning-text text-toggle'>{{ additional_text.collapsed|linebreaksbr }}<br><a class='text-toggle-action' href=''>show more</a></p>
{% endif %}

samples_manager/templates/samples_manager/partial_box_item_remove.html
<form method='post' action='{% url "samples_manager:box_item_remove" box.id %}'
    class='ui form js-submit-box-item-form js-box-item-remove-form'>
    {% csrf_token %}
    <div class='ui center aligned segment container'>
        <div class='ui centered header'>
            <h3>Confirm item removal</h3>
        </div>
        <p>Are you sure you want to perform this action? It is irreversible.</p>
        {% include 'samples_manager/form_collapsible_text.html' %}
        <div class='two ui buttons actions'>
            <button type='button' class='ui deny medium button'>Cancel</button>
            <button type='submit' class='ui negative medium button submit'>Remove</button>
        </div>
    </div>
</form>

samples_manager/templates/samples_manager/partial_dosimeter_delete.html
<form method='post' action='{% url "samples_manager:dosimeter_delete" %}'
    class='ui form js-submit-dosimeter-form js-dosimeter-delete-form'>
    {% csrf_token %}
    <div class='ui center aligned segment container'>
        <div class='ui centered header'>
            <h3>Confirm dosimeter deletion</h3>
        </div>
        <p>Are you sure you want to perform this action? It is irreversible.</p>
        {% include 'samples_manager/form_collapsible_text.html' %}
        <div class='two ui buttons actions'>
            <button type='button' class='ui deny medium button'>Cancel</button>
            <button type='submit' class='ui negative medium button submit'>Delete</button>
        </div>
    </div>
</form>

samples_manager/templates/samples_manager/partial_dosimeter_generate_dos_ids.html
<form method='post' action='{% url "samples_manager:create_dos_ids" %}' class='ui form js-submit-dosimeter-form js-generate-ids-form'>
    {% csrf_token %}
    <div class='ui center aligned segment container'>
        <div class='ui centered header'>
            <h3 class='modal-title'>Create dosimeter entries</h3>
        </div>
        {% for field in form %}
        {% include 'samples_manager/form_field.html' %}
        {% endfor %}
        <div class='two ui buttons actions'>
            <button type='button' class='ui deny medium button'>Cancel</button>
            <button type='submit' class='ui orange medium button submit'>Assign IDs</button>
        </div>
    </div>
</form>

samples_manager/templates/samples_manager/partial_experiment_samples_archive.html
{% load static %}
{% if pagination_data.double_pagination %}
<div id='partial-template-pagination-top'>
    {% include 'samples_manager/pagination.html' %}
</div>
{% endif %}
<div id='partial-template-table'>
    <table class='ui center aligned sortable celled table' id='data-table'>
        <thead>
            <tr>
                <th>Sample ID</th>
                <th>Sample Name</th>
                <th>Current experiment</th>
                <th>Timestamp of change</th>
            </tr>
        </thead>
        <tbody>
            {% for archive in archives %}
            <tr>
                <td>{{ archive.sample.set_id }}</td>
                <td>{{ archive.sample.name }}</td>
                <td>
                    <a href='{% url "samples_manager:experiment_samples_list" archive.sample.experiment.id  %}'>
                        {{archive.sample.experiment}}
                    </a>
                </td>
                <td>{{ archive.timestamp|date:"d/m/Y"}}</td>
            </tr>
            {% empty %}
            <tr>
                <td colspan='8' class='text-center'>There are no archived samples</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div id='partial-template-pagination-bottom'>
    {% include 'samples_manager/pagination.html' %}
</div>

samples_manager/templates/samples_manager/partial_sample_create_update_clone.html
{% load widget_tweaks %}
{% load static %}
<form method='post' action='{{ form_tag_action }}'
    class='ui form js-submit-sample-form js-sample-{{ form_action|lower }}-form'>
    {% csrf_token %}
    <div class='ui centered grid container'>
        <div class='ui text container'>
            <div class='three ui buttons center aligned grid container' style='margin:20px;'>
                <div class='ui big basic blue button{% if current_page != 1 %} unactive-tab{% endif %}' id='step-tab-1'>
                    <div class='content'>Step 1</div>
                </div>
                <div class='ui big blue basic button{% if current_page != 2 %} unactive-tab{% endif %}' id='step-tab-2'>
                    <div class='content'>Step 2</div>
                </div>
                <div class='ui big blue basic button{% if current_page != 3 %} unactive-tab{% endif %}' id='step-tab-3'>
                    <div class='content'>Step 3</div>
                </div>
            </div>
            <div id='steps'>
                <div id='step-1' class='transition {% if current_page == 1 %}visible{% else %}hidden{% endif %}'>
                    <div class='ui center aligned segment container'>
                        <div class='ui centered header'>
                            <h3>{{ form_action }} Sample</h3>
                            <p class='required form-description-area'>* required field</p>
                        </div>
                        {% for field in form1 %}
                        {% include 'samples_manager/form_field.html' %}
                        {% endfor %}
                        <div class='two ui buttons actions'>
                            <button type='button' class='ui deny medium button'>Cancel</button>
                            <button type='button' class='ui  inverted blue medium button next-step'>Next</button>
                        </div>
                    </div>
                </div>
                <div id='step-2' class='transition {% if current_page == 2 %}visible{% else %}hidden{% endif %}'>
                    <div class='ui center aligned segment container'>
                        <div class='image content'>
                            <div class='ui medium image'>
                                <img src='{% static "images/layers.png" %}' alt='Layer' width='100%'>
                            </div>
                        </div>
                        {% for field in form2 %}
                        {% include 'samples_manager/form_field.html' %}
                        {% endfor %}
                        <button type='button' id='create-compound' class='ui blue button js-load-compound-form js-create-compound'
                            data-url='{% url "samples_manager:compound_create" %}'>
                            <i class='plus icon'></i>Add new compound
                        </button>
                        <table class='ui celled table formset_table layer_formset'>
                            {{ layer_formset.management_form }}
                            {% for form in layer_formset.forms %}
                            {% include 'samples_manager/formset_table_head.html' %}
                            {% endfor %}
                            <tbody>
                                {% for form in layer_formset.forms %}
                                {% include 'samples_manager/formset_table_body_row.html' %}
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class='two ui buttons actions'>
                            <button type='button' class='ui  inverted blue  medium button prev-step'>Previous</button>
                            <button type='button' class='ui  inverted blue  medium button next-step'>Next</button>
                        </div>
                    </div>
                </div>
                <div id='step-3' class='transition {% if current_page == 3 %}visible{% else %}hidden{% endif %}'>
                    <div class='ui center aligned segment container'>
                        {% for field in form3 %}
                        {% include 'samples_manager/form_field.html' %}
                        {% endfor %}
                        <div class='two ui buttons actions'>
                            <button type='button' class='ui inverted blue medium button prev-step'>Previous</button>
                            <button type='submit' class='ui positive medium button submit'>Submit</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script type='text/javascript' src='{% static "js/jquery.formset.js" %}'></script>
<script type='text/javascript' src='{% static "js/steps.js" %}'></script>
<script type='text/javascript'>
    $(document).ready(function () {
        $('.formset_table.layer_formset .formset_row').formset({
            addText: 'Add Layer',
            deleteText: '×',
            prefix: '{{ layer_formset.prefix }}',
            formCssClass: 'dynamic-formset-{{ layer_formset.prefix }}',
            addCssClass: '{{ layer_formset.prefix }}-add-row',
            deleteCssClass: '{{ layer_formset.prefix }}-delete-row',
            added: activateSearchSelectFields
        });
        $('#id_set_id').click(function () {
            alert('Please, make sure you already have an assigned SET-ID from IRRAD or inforEAM.')
        });
        activateSearchSelectFields();
        activatePopups(500);
    });
</script>

samples_manager/templates/samples_manager/partial_samples_list.html
{% load static %}
{% load custom_filters %}
{% if pagination_data.double_pagination %}
<div id='partial-template-pagination-top'>
    {% include 'samples_manager/pagination.html' %}
</div>
{% endif %}
<div id='partial-template-table'>
    <table class='ui center aligned sortable celled table' id='data-table'>
        <thead>
            <tr>
                {% if experiment.status != 'Completed' %}
                <th class='sorttable_nosort'><input name='select_all' value='1'
                     id='all-checkbox' class='checkbox' type='checkbox' /></th>
                {% endif %}
                <th>Sample Name</th>
                <th>Sample ID</th>
                <th>Last update</th>
                <th>Category</th>
                <th>Requested fluence</th>
                <th>Radiation / Nu. Coll. / Nu. Int.<br>Length Occupancy (%)</th>
                <th>Last updated by</th>
                <th>Box</th>
            </tr>
        </thead>
        <tbody>
            {% for sample in samples %}
            <tr>
                {% if experiment.status != 'Completed' %}
                <td><input type='checkbox' class='checkbox' id='sample-{{sample.id}}' name='checks[]'
                    value='{{sample.id}}'>
                </td>
                {% endif %}
                <td><a href='{% url "samples_manager:sample_details" sample.experiment.id sample.id %}'>{{sample.name}}</a></td>
                {%if sample.set_id %}
                <td>{{sample.set_id}}</td>
                {% else %}
                <td>Not assigned</td>
                {% endif %}
                <td>{{sample.updated_at|date:"d/m/Y"}}</td>
                <td>{{sample.category}}</td>
                <td>{{sample.req_fluence.req_fluence|num_notation:'4e'}}</td>
                <td>{{sample.radiation_length_occupancy|num_notation:'3d'}} /
                    {{sample.nu_coll_length_occupancy|num_notation:'3d'}} /
                    {{sample.nu_int_length_occupancy|num_notation:'3d'}}</td>
                <td>{{sample.updated_by}}</td>
                {%if sample.box.box_id %}
                <td><a href='{% url "samples_manager:box_details" sample.box.id %}'>{{sample.box.box_id}}</a></td>
                {% else %}
                <td>Not assigned</td>
                {% endif %}
            </tr>
            {% empty %}
            <tr>
                <td colspan='10' class='text-center'>There are no samples</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div id='partial-template-pagination-bottom'>
    {% include 'samples_manager/pagination.html' %}
</div>
<script type='text/javascript' src='{% static "js/checkboxes.js" %}'></script>

samples_manager/templates/samples_manager/partial_write_box_infoream.html
<form method='post' action='{% url "samples_manager:box_write_infoream" %}'
    class='ui form js-submit-box-form'>
    {% csrf_token %}
    <div class='ui center aligned segment container'>
        <div class='ui centered header'>
            <h3>Confirm write to inforEAM</h3>
        </div>
        <p>Are you sure you want to perform this action? It is irreversible.</p>
        {% include 'samples_manager/form_collapsible_text.html' %}
        <div class='two ui buttons actions'>
            <button type='button' class='ui deny medium button'>Cancel</button>
            <button type='submit' class='ui positive medium button submit'>Confirm</button>
        </div>
    </div>
</form>

samples_manager/templates/samples_manager/users_list.html
{% extends 'samples_manager/base_all_tab_list.html' %}
{% load static %}

{% block modals %}
<div class='ui modal' id='modal-user'>
    <i class='close icon'></i>
    <div class='content modal-content'>
    </div>
</div>
{% endblock %}

{% block breadcrumb %}
<a class='section' href='{% url "samples_manager:index" %}'>Home</a>
<div class='divider'> / </div>
<div class='section'>Users</div>
{% endblock %}

{% block actions %}
<div class='two wide column'>
    <button type='button' class='ui blue tiny button action-button js-load-user-form' 
        id='user-create' title='Create user'
        data-url='{% url "samples_manager:user_create" %}'>
        <i class='plus icon'></i>Create
    </button>
</div>
<div class='two wide column'>
    <button type='button' class='ui tiny button action-button js-load-user-form single-action' 
        id='user-update' title='Update user'
        data-url='{% url "samples_manager:user_update" %}'>
        <i class='pencil icon'></i>Update
    </button>
</div>
<div class='two wide column'>
    <button type='button' class='ui red tiny button action-button js-load-user-form group-action' 
        id='user-delete' title='Delete user'
        data-url='{% url "samples_manager:user_delete" %}'>
        <i class='trash icon'></i>Delete
    </button>
</div>
{% endblock %}

{% block partial_template %}
{% include 'samples_manager/partial_users_list.html' %}
{% endblock %}

{% block javascript %}
<script type='text/javascript' src='{% static "js/users.js" %}'></script>
{% endblock %}